import type { Response, NextFunction } from 'express';
import { Invoice } from '../models/invoice.model.js';
import { type AuthenticatedRequest } from '../middlewares/auth.middleware.js';
import { generatePDF } from '../utils/pdfGenerator.js';
import { generateInvoiceHtml } from '../utils/invoice-template.js';
import { emailService } from '../utils/emailService.js';

/**
 * Controller for invoice operations.
 */
export const createInvoice = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const invoiceData = req.body;
    const userId = req.user!._id;

    const newInvoice = await Invoice.create({
      ...invoiceData,
      userId
    });

    res.status(201).json({
      success: true,
      message: 'Invoice created successfully',
      data: newInvoice
    });
  } catch (error) {
    next(error);
  }
};

export const getInvoiceById = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user!._id;

    const invoice = await Invoice.findOne({ _id: id, userId } as any);

    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found or unauthorized'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: invoice
    });
  } catch (error) {
    next(error);
  }
};

export const sendInvoiceEmail = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const { recipientEmail, subject, message } = req.body;
    const userId = req.user!._id;

    const invoice = await Invoice.findOne({ _id: id, userId } as any);
    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found or unauthorized'
      });
      return;
    }

    // 1. Generate PDF
    const html = generateInvoiceHtml(invoice);
    const pdfBuffer = await generatePDF(html);

    // 2. Send Email
    await emailService.sendEmail({
      to: recipientEmail,
      subject: subject || `Invoice from ${invoice.billFrom.businessName}`,
      html: `
        <div style="font-family: sans-serif; line-height: 1.5; color: #333;">
          <p>${message.replace(/\n/g, '<br>')}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 0.875rem; color: #666;">Generated by AI Invoicer</p>
        </div>
      `,
      attachments: [
        {
          filename: `invoice-${id}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    });

    // 3. Update Status
    invoice.status = 'SENT';
    await invoice.save();

    res.status(200).json({
      success: true,
      message: 'Email sent successfully!'
    });
  } catch (error) {
    next(error);
  }
};

export const getAllInvoices = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 7;
    const search = req.query.search as string;
    const status = req.query.status as string;
    const skip = (page - 1) * limit;
    const userId = req.user!._id;

    // Check for overdue invoices and update them
    const now = new Date();
    await Invoice.updateMany(
      {
        userId,
        status: 'SENT',
        dueDate: { $lt: now.toISOString() }
      },
      { $set: { status: 'OVERDUE' } }
    );

    const query: Record<string, unknown> = { userId };

    if (status) {
      const upperStatus = status.toUpperCase();
      if (['DRAFT', 'SENT', 'PAID', 'OVERDUE'].includes(upperStatus)) {
        query.status = upperStatus;
      }
    }

    if (search) {
      query.$or = [
        { 'billTo.clientName': { $regex: search, $options: 'i' } },
        { 'billTo.clientEmail': { $regex: search, $options: 'i' } }
      ];
    }

    // Fetch total count and paginated data in parallel
    const [total, invoices] = await Promise.all([
      Invoice.countDocuments(query),
      Invoice.find(query).lean().sort({ createdAt: -1 }).skip(skip).limit(limit)
    ]);

    res.status(200).json({
      success: true,
      data: invoices,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

export const updateInvoiceStatus = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    const userId = req.user!._id;

    const validStatuses = ['DRAFT', 'SENT', 'PAID', 'OVERDUE'];
    if (!validStatuses.includes(status)) {
      res.status(400).json({
        success: false,
        message: 'Invalid status'
      });
      return;
    }

    const invoice = await Invoice.findOneAndUpdate(
      { _id: id, userId } as any,
      { status },
      { returnDocument: 'after' }
    );

    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found or unauthorized'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Invoice status updated successfully',
      data: invoice
    });
  } catch (error) {
    next(error);
  }
};

export const updateInvoice = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const updateData = req.body;
    const userId = req.user!._id;

    const invoice = await Invoice.findOneAndUpdate(
      { _id: id, userId } as any,
      updateData,
      {
        returnDocument: 'after',
        runValidators: true
      }
    );

    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found or unauthorized'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Invoice updated successfully',
      data: invoice
    });
  } catch (error) {
    next(error);
  }
};

export const deleteInvoice = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user!._id;

    const invoice = await Invoice.findOneAndDelete({ _id: id, userId } as any);

    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found or unauthorized'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Invoice deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};
