import type { Request, Response, NextFunction } from 'express';
import { Invoice } from '../models/invoice.model.js';
import { User } from '../models/user.model.js';
import { generatePDF } from '../utils/pdfGenerator.js';
import { generateInvoiceHtml } from '../utils/invoice-template.js';
import { emailService } from '../utils/emailService.js';

/**
 * Controller for invoice operations.
 */
export const createInvoice = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const invoiceData = req.body;

    // Temporary singleton user approach until auth is fully implemented.
    const user = await User.findOne();
    if (!user) {
      res.status(404).json({
        success: false,
        message: 'No user found. Please create a profile first.'
      });
      return;
    }

    const newInvoice = await Invoice.create({
      ...invoiceData,
      userId: user._id
    });

    res.status(201).json({
      success: true,
      message: 'Invoice created successfully',
      data: newInvoice
    });
  } catch (error) {
    next(error);
  }
};

export const getInvoiceById = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const invoice = await Invoice.findById(id);

    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: invoice
    });
  } catch (error) {
    next(error);
  }
};

export const sendInvoiceEmail = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const { recipientEmail, subject, message } = req.body;

    const invoice = await Invoice.findById(id);
    if (!invoice) {
      res.status(404).json({
        success: false,
        message: 'Invoice not found'
      });
      return;
    }

    // 1. Generate PDF
    const html = generateInvoiceHtml(invoice);
    const pdfBuffer = await generatePDF(html);

    // 2. Send Email
    await emailService.sendEmail({
      to: recipientEmail,
      subject: subject || `Invoice from ${invoice.billFrom.businessName}`,
      html: `
        <div style="font-family: sans-serif; line-height: 1.5; color: #333;">
          <p>${message.replace(/\n/g, '<br>')}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 0.875rem; color: #666;">Generated by AI Invoicer</p>
        </div>
      `,
      attachments: [
        {
          filename: `invoice-${id}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    });

    // 3. Update Status
    invoice.status = 'SENT';
    await invoice.save();

    res.status(200).json({
      success: true,
      message: 'Email sent successfully!'
    });
  } catch (error) {
    next(error);
  }
};
