import { config } from 'dotenv';
config({ path: '.env' });

export const {
  PORT,
  FRONTEND_URL,
  NODE_ENV,
  DB_URI,
  ARCJET_KEY,
  ARCJET_ENV,
  SMTP_USER,
  BREVO_API_KEY,
  GEMINI_API_KEY,
  GEMINI_MODEL,
  JWT_SECRET,
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
  STRIPE_PROFESSIONAL_PRICE_ID,
  STRIPE_ENTERPRISE_PRICE_ID
} = process.env;
